version: '3'

services:
  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data